#!/usr/bin/env sh
set -eu

HOST_UID=$(id -u)
HOST_GID=$(id -g)

cat > .env <<EOF
# Generated by scripts/init_vps.sh for this host.
BLOODLINES_UID=${HOST_UID}
BLOODLINES_GID=${HOST_GID}
EOF

mkdir -p data/input data/output

if [ ! -w data/input ] || [ ! -w data/output ]; then
  echo "VPS initialization failed: ./data must be writable by the current user." >&2
  echo "Current user: $(id -un) (${HOST_UID}:${HOST_GID})" >&2
  echo "Fix checkout ownership, for example:" >&2
  echo "  sudo chown -R $(id -un):$(id -gn) $(pwd)" >&2
  exit 1
fi

echo "Historical Bloodlines VPS environment initialized"
echo "Host user: $(id -un) (${HOST_UID}:${HOST_GID})"
echo "Compose environment: $(pwd)/.env"
